// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCr22WjT7sfbMx4pB0m1AZGBukY5i84-A',
    appId: '1:268601263672:web:c912725b4f39f6482888cd',
    messagingSenderId: '268601263672',
    projectId: 'utech-flutter-batch-2',
    authDomain: 'utech-flutter-batch-2.firebaseapp.com',
    databaseURL:
        'https://utech-flutter-batch-2-default-rtdb.firebaseio.com/', // IMPORTANT!
    storageBucket: 'utech-flutter-batch-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJatgOi22Un9Wu3RiH0Yvfz8n36RXINdY',
    appId: '1:268601263672:android:2383715dd9db79c22888cd',
    messagingSenderId: '268601263672',
    projectId: 'utech-flutter-batch-2',
    databaseURL:
        'https://utech-flutter-batch-2-default-rtdb.firebaseio.com/', // IMPORTANT

    storageBucket: 'utech-flutter-batch-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkYdk5nq3fEOWhB0fdvPaoiVHMrQ-WncY',
    appId: '1:268601263672:ios:1f58177815ba5c8d2888cd',
    messagingSenderId: '268601263672',
    projectId: 'utech-flutter-batch-2',
    storageBucket: 'utech-flutter-batch-2.appspot.com',
    databaseURL:
        'https://utech-flutter-batch-2-default-rtdb.firebaseio.com/', // IMPORTANT!

    iosBundleId: 'com.example.class19',
  );
}
